// anms-ui/angular-port/anms-ui/src/app/features/management/agents/crud/crud.ts
import {Component, inject, Input} from '@angular/core';
import {ApiService} from '../../../../shared/api.service';
import {ToastrService} from 'ngx-toastr';
import {FormsModule} from '@angular/forms';

export interface Operation {
  command_name: string;
  command_parameters: string[];
  agent_parameter_id: number | string;
  // any other fields you may have
}

interface ParamModel {
  name: string;
  value: string;
}

@Component({
  selector: 'app-crud',
  imports: [
    FormsModule
  ],
  templateUrl: './crud.html',
  styleUrl: './crud.css',
})
export class Crud {
  @Input() agentId!: number | string;
  @Input() operations: Operation[] = [];
  private apiService = inject(ApiService);
  private toastr = inject(ToastrService)

  selected: Operation | -1 = -1;
  params: ParamModel[] = [];
  finalValues: Record<string, string> = {};

  onOperationChange(): void {
    // Clear existing params
    this.params = [];

    if (this.selected === -1 || !this.selected) {
      return;
    }

    const commandParameters = this.selected.command_parameters || [];
    commandParameters.forEach((value) => {
      this.params.push({name: value, value: ''});
    });
  }

  onClick(): void {
    if (this.selected === -1 || !this.selected) {
      this.toastr.warning('Please select an operation first.');
      return;
    }

    this.finalValues = {};
    this.params.forEach((param) => {
      this.finalValues[param.name] = param.value;
    });

    this.apiService
      .apiPutCRUD(this.agentId, this.selected.agent_parameter_id, this.finalValues)
      .subscribe({
        next: (response: any) => {
          this.toastr.success(`${response.statusText} ${response.data}`);
          this.selected = -1;
          this.params = [];
        }, error: (error: any) => {
          console.error('crud error', error);
          this.toastr.error(error);
        }
      });
  }
}

// anms-ui/public/app/components/management/agents/crud.vue
<template>
  <div>
    <!-- what are the inputs  -->
    <!-- request name -->
    <!-- request input -->
    <p>Operation: </p>
    <select v-model="selected" @change="setParams(selected.command_parameters)">
      <option disabled value="-1">-- Select Operation --</option>
      <option v-for="opt, index in Operations" :key="index" :value="opt">{{ opt.command_name }}</option>
    </select>
    <div v-for="(param) in params" v-bind:key="param.name">
      {{ param.name }}::
      <input v-b-tooltip.hover type="string" name="parms" v-model="param.value" />
    </div>
    <button @click="onClick()">Send Parameter</button>

    <div>
      [{{ results }}]
    </div>
  </div>
</template>

<script>
import { values } from 'lodash'
import api from '../../../shared/api'

export default {
  name: "CRUD",
  props: ["agentId", "Operations"],
  data() {
    return {
      selected: -1,
      headers: [],
      title: "",
      results: "",
      results2: "",
      params: [],
      final_values: {}
    }

  }, methods: {

    setParams(command_parameters) {
      command_parameters.forEach((value) => {
        this.results2 = value;
        this.params.push({ "name": value, "value": "" });
      });

      this.results = command_parameters;
    },
    onClick() {
      this.final_values = {}
      this.params.forEach((param) =>
        this.final_values[param.name] = param.value
      )
      api.methods
        .apiPutCRUD(this.agentId, this.selected.agent_parameter_id, this.final_values)
        .then((response) => {
          this.results = "SENT! "+ response.data + " " + response.statusText ;
          this.selected = -1;
          this.params = []
        })
        .catch((error) => {
          this.results = "ERROR sending " + error
          console.error(error);
        })
    },
  },
  computed: {
  },
  mounted() {
  }
}


</script>
<style scoped></style>
