// anms-ui/angular-port/anms-ui/src/app/features/management/agents/reports/reports.ts
import {Component, inject, Input, OnInit} from '@angular/core';
import {ToastrService} from 'ngx-toastr';
import {ApiService} from '../../../../shared/api.service';
import {FormsModule} from '@angular/forms';

export interface ReportOption {
  exec_set: string;
  nonce_cbor: string;
}

@Component({
  selector: 'app-reports',
  templateUrl: './reports.html',
  styleUrls: ['./reports.css'],
  imports: [
    FormsModule
  ]
})
export class Reports implements OnInit {
  @Input() agentName!: string;
  @Input() rptts: ReportOption[] = [];
  @Input() registeredAgentsId!: string;

  apiService = inject(ApiService);
  toastr = inject(ToastrService);

  selected?: ReportOption;
  tableHeaders: string[][] = [];
  tableItems: any[][][] = [];
  title = '';
  reports: Record<string, any> = {};
  reportsHeader: Record<string, any> = {};
  loading = true;

  constructor() { }

  ngOnInit(): void {
    this.loading = true;
    console.log('rptts', this.rptts);

    // preload all reports like in mounted()
    const preloadPromises = this.rptts.map((rpt, index) =>
      this.apiService
        .apiEntriesForReport(this.registeredAgentsId, rpt.nonce_cbor)
        .subscribe({
          next: (res: any) => {
            console.log('report', index, res);
            this.reports[index] = res;
          }, error: (error: any) => {
            console.error('reports error', error);
          }
        })
    );

    Promise.all(preloadPromises)
      .finally(() => {
        this.loading = false;
      });
  }

  async onReportSelect(): Promise<void> {
    if (!this.selected) {
      return;
    }

    this.loading = true;
    this.tableHeaders = [];
    this.tableItems = [];

    const nonce_cbor = this.selected.nonce_cbor;

    try {
      const res: any = this.apiService.apiEntriesForReport(
        this.registeredAgentsId,
        encodeURIComponent(nonce_cbor)
      );

      this.processReport(res.data);

      const key = JSON.stringify(this.selected);
      this.reports[key] = this.tableItems;
      this.reportsHeader[key] = this.tableHeaders;
    } catch (error: any) {
      console.error('reports error', error);
      this.toastr.error('reports error: ' + error);
    } finally {
      this.loading = false;
    }
  }

  private processReport(report: any): void {
    let rpt: any[] = [];

    if (this.selected && this.selected.exec_set in report) {
      rpt = report[this.selected.exec_set];
    } else if (this.selected) {
      rpt = report[this.selected.nonce_cbor];
    }

    if (!rpt || rpt.length === 0) {
      return;
    }

    // header from first item keys
    const holdHeader: string[] = Object.keys(rpt[0]);

    const currTableItems: any[][] = [];

    for (const item of rpt) {
      const row: any[] = [];
      for (const h of holdHeader) {
        row.push(item[h]);
      }
      currTableItems.push(row.flat());
    }

    this.tableHeaders.push(holdHeader);
    this.tableItems.push(currTableItems);
  }
}

// anms-ui/public/app/components/management/agents/reports.vue
<template>
  <div>
    <h5>Reports sent:</h5>
    <div v-if="loading"
      class="spinner-border text-primary"
      role="status">
      <span class="sr-only">Loading...</span>
    </div>
    <v-select 
        :options="rptts" 
        label="exec_set"
        v-model="selected"
        @option:selected="onReportSelect()"></v-select>
    <div v-for="(_, index) in tableItems" :key="index">
      <b-table id="report-table" :items="tableHeaders[index]" thead-class="d-none"/>
      <div class="scrollable-div">
        <b-table 
        bordered
        striped
        responsive
        v-if="!loading && selected != -1"
        id="report-table" :items="tableItems[index]" 
        thead-class="d-none" />
      </div>
    </div>
  </div>
</template>

<script>
import api from '../../../shared/api'
import toastr from "toastr";
import vSelect from "vue-select";

export default {
  name: "reports",
  components: {
    vSelect
  },
  props: ["agentName", "rptts", "registered_agents_id"],
  data() {
    return {
      selected: undefined,
      test: "",
      tableHeaders: [],
      tableItems: [],
      title: "",
      reports: {},
      reportsHeader: {},
      loading: true,
    }
  },
  methods: {
    async onReportSelect() {
      this.loading = true;
      this.tableHeaders = [];
      this.tableItems = [];
      this.loading = true;
      let nonce_cbor = this.selected.nonce_cbor;
    
      await api.methods.apiEntriesForReport(this.registered_agents_id,encodeURIComponent(nonce_cbor))
        .then(res => {
          this.processReport(res.data);
          this.reports[this.selected] = this.tableItems;
          this.reportsHeader[this.selected] = this.tableHeaders;
        }).catch(error => {
          // handle error
          console.error("reports error", error);
          toastr.error("reports error: " + error)
        });
    
      this.loading = false;
    },
    processReport(report) {
      let rpt = [];
      if(this.selected.exec_set in report){
        rpt = report[this.selected.exec_set];
      }else{
        rpt = report[this.selected.nonce_cbor];
      }

      let currTableItems = [];
      // let holdHeader = rpt.shift();
      
      console.log(rpt);
      
      let holdHeader = Object.keys(rpt[0]);
      console.log(holdHeader);
      for (let item of rpt) {
          let row = [];
          for (let hI of holdHeader) {
            row.push(item[hI]);
          }
          currTableItems.push(row.flat());
          console.log(currTableItems);
        }
    
      this.tableHeaders.push([holdHeader]);
      this.tableItems.push(currTableItems);
    }
  },
  computed: {
  },
  mounted() {
    this.loading = true;
    this.rptts.forEach((rpt, index) => {
      api.methods.apiEntriesForReport(this.registered_agents_id, rpt.nonce_cbor)
        .then(res => {
          this.reports[index] = res.data
        }).catch(error => {
          // handle error
          console.error("reports error", error);
          console.log("error obj:", error);

        });
    });
    this.loading = false;
  },
}


</script>
<style scoped>
.spacing-table {
  margin: 16px 0;
}
.select-max-width {
  max-width: 600px;
}
.b-table-sticky-header > .table.b-table > thead > tr > th {
  position: sticky !important;
}
.scrollable-div {
  max-height: 600px; /* Set a maximum height for the div */
  overflow-y: auto; /* Add a vertical scrollbar when content exceeds max-height */
  /* overflow-y: scroll; /* Always show a vertical scrollbar */
}
</style>
