// anms-ui/public/app/components/management/agents/Agents.vue
<template>
  <div>
    <b-row>
      <b-col offset="2"
        cols="8">
        <div class="input-group mb-3">
          <input type="text"
            class="form-control"
            placeholder="Search by ID String, First Registered, or Last Registered"
            v-model="searchString"
            @change="handleSearchStringChange($event)"
            v-on:keyup.enter="handlePageChange(1)" />
          <div class="input-group-append">
            <div class="d-grid gap-2 col-6 mx-auto">
            <button class="btn btn-outline-secondary"
              type="button"
              @click="handlePageChange(1)">
              Search
            </button>
          </div>
          </div>
        </div>
        <b-row>
          <b-col>
            <p>Select Agent to view</p>
          </b-col>
          <b-col><button class="btn btn-outline-success float-right mb-2"
              @click="goToManageModal"
              :disabled="!selectedAgents.length">Manage</button></b-col>
        </b-row>
        <b-table id="agents-table"
          ref="agentsTable"
          :items="currentAgents"
          :fields="fields"
          :per-page="pageSize"
          @row-clicked="goToAgentDetails"
          primary-key="registered_agents_id"
          hover
          bordered>
          <template #head(selected)="data">
            <div style="text-align: center;">
              <b-form-checkbox v-model="selectAll"
                @change="toggleSelectAll">Select All</b-form-checkbox>
            </div>
          </template>
          <template #cell(selected)="{ item }">
            <div style="text-align: center;">
              <b-form-checkbox :checked="item.selected"
                @change="selectAgent($event, item)"></b-form-checkbox>
            </div>
          </template>
        </b-table>
        <b-row>
          <b-col>
            <b-input-group prepend="Agent Address">
              <b-form-input v-model="node"></b-form-input>
              <b-input-group-append>
                <b-button variant="outline-success"
                  @click="onClick(node.trim())">Add</b-button>
              </b-input-group-append>
            </b-input-group>
          </b-col>
          <b-col>
            <div class="d-flex float-right">
              <div class="my-2 mx-3">
                Items per Page:
                <select v-model="pageSize"
                  @change="handlePageSizeChange($event)">
                  <option v-for="size in pageSizes"
                    :key="size"
                    :value="size">
                    {{ size }}
                  </option>
                </select>
              </div>
              <b-pagination v-model="page"
                class="m-0"
                :total-rows="count"
                :per-page="pageSize"
                aria-controls="agents-table"
                @change="handlePageChange">
              </b-pagination>
            </div>
          </b-col>
        </b-row>
      </b-col>
    </b-row>

    <agent-modal @close="showAgentModal = false"
      :showModal="showAgentModal"
      :agentInfo="agentInfo"></agent-modal>

    <agents-manage-modal @close="showManageModal = false"
      :showModal="showManageModal"
      :agents="selectedAgents"
      :cbor="cbor"
      :cbors="cbors"></agents-manage-modal>

    <footer class="footer">
      <p><a>Amp Version: {{ info }}</a></p>
    </footer>
  </div>
</template>

<script>
import { mapGetters, mapActions } from "vuex";
import api from "../../../shared/api.js";
import AgentModal from "./AgentModal.vue";
import AgentsManageModal from "./AgentsManageModal.vue";
import toastr from "toastr";

export default {
  name: "Agents",
  components: {
    AgentModal,
    AgentsManageModal,
  },
  data() {
    return {
      fields: [
        {
          key: "selected",
          sortable: false,
        },
        {
          key: "agent_id_string",
          sortable: false,
        },
        {
          key: "first_registered",
          sortable: false,
        },
        {
          key: "last_registered",
          sortable: false,
        },
      ],
      node: null,
      info: "",
      results: "",
      pageSizes: [10, 20, 50, 100],
      nodes: "",
      selected: null,
      showAgentModal: false,
      showManageModal: false,
      agentInfo: null,
      selectAll: false,
    };
  },
  props: {
    cbor: {
      type: String,
      default: undefined
    },
    cbors: {
      type: Array,
      default: []
    }
  },
  mounted() {
    const vm = this;
    vm.reloadAgents();
    api.methods
      .apiAmpVersion()
      .then((response) => {
        if(response.data.build_date != null){
          vm.info = response.data.build_date + " " + response.data.build_time;
        }
      })
      .catch(function (error) {
        console.error(error);
        this.info = "failed to reach manager";
      });
  },
  computed: {
    ...mapGetters("agents", {
      currentAgents: "currentAgents",
      count: "count",
      page: "page",
      pageSize: "pageSize",
      searchString: "searchString",
    }),
    selectedAgents() {
      return this.currentAgents.filter((agent) => {
        return agent.selected == true;
      });
    },
  },
  methods: {
    ...mapActions("agents", {
      reloadAgents: "reloadAgents",
      setPage: "setPage",
      setPageSize: "setPageSize",
      setSearchString: "setSearchString",
      updateAgent: "updateAgent",
    }),
    goToAgentDetails(event) {
      this.agentInfo = event;
      this.showAgentModal = true;
    },
    goToManageModal() {
      this.showManageModal = true;
    },
    handlePageChange(value) {
      const vm = this;
      vm.setPage(value);
      vm.reloadAgents();
    },
    handlePageSizeChange(event) {
      const vm = this;
      vm.setPageSize(event.target.value);
      vm.setPage(1);
      vm.reloadAgents();
    },
    handleSearchStringChange(event) {
      const vm = this;
      vm.setSearchString(event.target.value);
    },
    onClick(nodes) {
      let nodeList = nodes.split(",");
      nodeList.forEach((node) => {
        api.methods
          .apiPostAgent(node.trim())
          .then((response) => {
            this.results = response.status + " " + response.statusText;
            toastr.success(this.results);
            
          })
          .catch((error) => {
            console.error(error);
            toastr.error(error);

          });
      });
    },
    getAgentIndexById(agentId) {
      return this.currentAgents.findIndex(agent => agent.registered_agents_id === agentId);
    },
    selectAgent(event, agent) {
      if (agent && event != agent.selected) {
        let agentUpdated = { ...agent };
        let agentIndex = this.getAgentIndexById(agentUpdated.registered_agents_id);
        agentUpdated.selected = event;
        this.updateAgent({ agentIndex, agent: agentUpdated });
      }
    },
    toggleSelectAll() {
      this.currentAgents.forEach((agent) => { this.selectAgent(this.selectAll, agent) });
    },
  },
};
</script>

<style>

.footer {
  position: fixed;
  bottom: 0;
}
</style>

// anms-ui/angular-port/anms-ui/src/app/features/management/agents/agents.ts
import {AfterViewInit, Component, inject} from '@angular/core';
import {AgentsService} from '../../../store/modules/agents.service';
import {ApiService} from '../../../shared/api.service';
import {FormsModule} from '@angular/forms';
import * as toastr from 'toastr';
import {MatPaginator, PageEvent} from '@angular/material/paginator';
import {MatDialog} from '@angular/material/dialog';
import {AgentInfo, AgentModal} from './agent-modal/agent-modal';

@Component({
  selector: 'app-agents',
  imports: [
    FormsModule,
    MatPaginator
  ],
  templateUrl: './agents.html',
  styleUrl: './agents.css',
})
export class Agents implements AfterViewInit {
  protected agentsService = inject(AgentsService);
  protected apiService = inject(ApiService);
  protected dialog = inject(MatDialog);

  protected info: string = '';
  protected selectAll: boolean = false;
  protected node: any;
  protected pageSizes = [10, 20, 50, 100];


  ngAfterViewInit(): void {
    this.agentsService.reloadAgents();
    this.apiService.apiAmpVersion().subscribe(
      {
        next: (response: any) => {
          if (response.build_date != null) {
            this.info = response.build_date + " " + response.build_time;
          }
        },
        error: (err: any) => {
          console.error(err);
          this.info = "failed to reach manager";
        }
      });
  }

  protected handleSearchStringChange($event: any) {
    this.agentsService.setSearchString($event.target.value);
  }

  protected handlePageEvent(pageEvent: PageEvent, paginator: MatPaginator) {
    if(this.agentsService.getPageSize() !== pageEvent.pageSize) {
      this.agentsService.setPageSize(pageEvent.pageSize);
      this.agentsService.setPage(1);
      paginator.firstPage()
    } else {
      this.agentsService.setPage(pageEvent.pageIndex + 1);
    }

    this.agentsService.reloadAgents();
  }

  protected toggleSelectAll() {
    this.agentsService.currentAgents().forEach((agent) => {
      this.selectAgent(this.selectAll, agent);
    });
  }

  protected selectAgent(event: any, agent: any) {
    if (agent && event != agent.selected) {
      let agentUpdated = {...agent};
      let agentIndex = this.getAgentIndexById(agentUpdated.registered_agents_id);
      agentUpdated.selected = event;
      this.agentsService.updateAgent(agentIndex, agentUpdated);
    }
  }

  protected onClick(nodes: string) {
    let nodeList = nodes.split(",");
    nodeList.forEach((node) => {
      this.apiService
        .apiPostAgent(node.trim())
        .subscribe({next: (response) => {
          const results = response.status + " " + response.statusText;
          toastr.success(results);
        },
          error: (err: any) => {
            console.error(err);
            toastr.error("Failed to add agent to node: " + node);
          }
        });
    });
  }

  protected selectedAgents() {
    return this.agentsService.currentAgents().filter((agent) => {
      return agent.selected == true;
    });
  }

  protected goToAgentDetails(agentInfo: AgentInfo) {
    const dialogRef = this.dialog.open(AgentModal, {
      width: '80vw',
      maxWidth: '1000px',
      data: agentInfo
    });

    dialogRef.afterClosed().subscribe(() => {
    });
  }

  protected goToManageModal() {
    // this.showManageModal = true;
  }

  private getAgentIndexById(agentId: any) {
    return this.agentsService.currentAgents().findIndex(agent => agent.registered_agents_id === agentId);
  }
}
